DISCORD_BOT1_TOKEN=MTQ2ODA5MDM0Njk2ODcxNTQwNQ.Gnc4uK.UnLY-nXS1_ZA7LmyK68qH2tkwsmpBAc9bPbico
DISCORD_BOT2_TOKEN=MTQ2ODA5MTA4NDQ2NjAzMjY4Mw.G1vL1s.t2OYMy9S_wG8qBSc7fAzs_RIDBJa0sh23AvFDo
DISCORD_CHANNEL_ID=1468104899760881807
HUGGINGFACE_TOKEN=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
